
package demo.ws.soap_spring_cxf_wss4j;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GreetingService", targetNamespace = "http://soap_spring_cxf_wss4j.ws.demo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GreetingService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://soap_spring_cxf_wss4j.ws.demo/", className = "demo.ws.soap_spring_cxf_wss4j.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://soap_spring_cxf_wss4j.ws.demo/", className = "demo.ws.soap_spring_cxf_wss4j.GreetResponse")
    public String greet(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
